crowd-size: 1000
max-visits: 4
pulse-resolution: 10
pulse-resolution-error: 5
meters-to-unit: 1
location-error: 20
start-time-range: 10
vel: 1.4
vel-error: 0.4
start-date-year: 2016
start-date-month: 6
start-date-day: 22
start-date-hour: 10
start-date-minute: 0
start-date-second: 0
wait-min: 10 
wait-max: 200
starting-locations: 
  - Entrances
points-of-interest:
  - Stages
  - Stages
  - Stages
  - Stages
  - Toilets
