crowd-size: 6
max-visits: 10
pulse-resolution: 7
pulse-resolution-error: 3
meters-to-unit: 10
location-error: 0.5
start-time-range: 5000
vel: 1.4
vel-error: 1.0
start-date-year: 2016
start-date-month: 6
start-date-day: 22
start-date-hour: 10
start-date-minute: 0
start-date-second: 0
starting-locations:
  -
    x: 0
    y: 0
  - 
    x: 10
    y: 10

points-of-interest:
  -
    name: point A
    x: 5
    y: 5
  -
    name: point B
    x: 2
    y: 7
  -
    name: point C
    x: 7
    y: 2
  -
    name: point D
    x: 9
    y: 7

