crowd-size: 1000
max-visits: 4
pulse-resolution: 0.08
pulse-resolution-error: 0.1
meters-to-unit: 0.1
location-error: 50
start-time-range: 1000
vel: 0.9
vel-error: 0.4
start-date-year: 2016
start-date-month: 6
start-date-day: 22
start-date-hour: 10
start-date-minute: 0
start-date-second: 0
wait-min: 5 
wait-max: 300
starting-locations: 
  - Entrances
points-of-interest:
  - Stages
  - Stages
  - Stages
  - Stages
  - Toilets
  - Campsites
  - Carparks
