crowd-size: 60
max-visits: 10
pulse-resolution: 50
pulse-resolution-error: 3
meters-to-unit: 10
location-error: 0.5
start-time-range: 50
vel: 1.4
vel-error: 1.0
start-date-year: 2016
start-date-month: 6
start-date-day: 22
start-date-hour: 10
start-date-minute: 0
start-date-second: 0
starting-locations:
  -
    x: -288443.7429
    y: 6649452.477

points-of-interest:
  -
    name: John Peel Stage
    x: -288443.7429
    y: 6649452.477
  -
    name: Pyramid Stage
    x: -287899.3211
    y: 6648847.965
  -
    name: Acoustic Stage
    x: -286909.9994
    y: 6648544.427
  -
    name: Theatre Astro Labe
    x: -287069.2061
    y: 6648189.415
  -
    name: Circus Big Top
    x: -287374.2867
    y: 6648140.268


